name: Run codecov

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
